<a href="https://colab.research.google.com/github/fafa20252025/fariba/blob/main/pandasexercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [418]:
import pandas as pd

In [419]:
s= pd.Series([10,20,30,40,50])
s.name="calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [420]:
s.dtype

dtype('int64')

In [421]:
s.values

array([10, 20, 30, 40, 50])

In [422]:
s.index

RangeIndex(start=0, stop=5, step=1)

**##indexing**

In [423]:
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [424]:
s[2:4]

2    30
3    40
Name: calories, dtype: int64

##ILOC find the location based on Numerical indexing

In [425]:
s.iloc[3]   #iloc function is only used for Numerical indices.

np.int64(40)

In [426]:
s.iloc[[1,2,3]]

1    20
2    30
3    40
Name: calories, dtype: int64

##To change the name of indecs

In [427]:
index=["apple","banana","grape","orange","strawberry"]
s.index=index   #s is an object and index is the attribute of object (s)
s

apple         10
banana        20
grape         30
orange        40
strawberry    50
Name: calories, dtype: int64

In [428]:
s["grape"]  # to find the calory of grapes

np.int64(30)

# LOC function is for finding label based indices.

In [429]:
s.loc["banana"]

np.int64(20)

in label base indexing, start and stop value are both included in output.

In [430]:
s["banana":"grapes"]

banana    20
grape     30
Name: calories, dtype: int64

# **##Creating series using a dictionary**

**1- create a dictionary**

In [431]:
fruit_protein = {
    "avodado" :2.3,
    "banana"  :1.2,
    "apple"   :1.3,
    "kiwi"    :2.1,
    "mango"   :2.4,
    "cherries":2.4
}

**2- create a series of the above dictionary**

In [432]:
s2=pd.Series(fruit_protein, name="protein")
s2  #print series

avodado     2.3
banana      1.2
apple       1.3
kiwi        2.1
mango       2.4
cherries    2.4
Name: protein, dtype: float64

# **Conditional selection**
exp: show all fruits that have protein over 2 grams
(Boolean indexing)

In [433]:
s2[s2>2]

avodado     2.3
kiwi        2.1
mango       2.4
cherries    2.4
Name: protein, dtype: float64

# **Logical operators**
True and True =True ,
True and False =False ,
False and False=False ,
True or True= True ,
True or False =True ,
False or Flase=Flse ,

In [434]:
# show fruits which have greater than 1 but have less than 2 gram protein.

s2[(s2>1)&(s2<2)]

banana    1.2
apple     1.3
Name: protein, dtype: float64

In [435]:
#not operation  not freater than 1.2
s2[~(s2>1.2)]

banana    1.2
Name: protein, dtype: float64

# **Modifying the series**

In [436]:
#modify the protein of a fruit
s2["banana"]=3
s2

avodado     2.3
banana      3.0
apple       1.3
kiwi        2.1
mango       2.4
cherries    2.4
Name: protein, dtype: float64

In [437]:
import numpy as np

In [438]:
ser= pd.Series(["a", np.nan, 1, np.nan, 2])
s.notnull().sum()

np.int64(5)

# **DataFrame**
 we only use LOC and ILOC functions in dataframe

In [439]:
# create dictionary
data={
    "name": ["alice", "bob", "charlie","eve" "david","alice"],
    "age": [25, 30, 35,33, 40,25],
    "department": ["hr", "IT","finance","HR","IT","hr"],
    "salary": [50000, 60000, 70000,5000, 80000,50000]
}
data  #print data

{'name': ['alice', 'bob', 'charlie', 'evedavid', 'alice'],
 'age': [25, 30, 35, 33, 40, 25],
 'department': ['hr', 'IT', 'finance', 'HR', 'IT', 'hr'],
 'salary': [50000, 60000, 70000, 5000, 80000, 50000]}

In [440]:
data={
    "name": ["alice", "bob", "charlie","eve", "david","alice"],
    "age": [25, np.nan, 35,33, 40,25],
    "department": ["hr", "IT","finance","HR","IT","hr"],
    "salary": [50000, 60000, 70000,np.nan, 80000,50000]
}
df=pd.DataFrame(data)  #convert the above dictionary to dataframe
df

      name   age department   salary
0    alice  25.0         hr  50000.0
1      bob   NaN         IT  60000.0
2  charlie  35.0    finance  70000.0
3      eve  33.0         HR      NaN
4    david  40.0         IT  80000.0
5    alice  25.0         hr  50000.0

In [441]:
df.head(2)  #print only first 2 rows

    name   age department   salary
0  alice  25.0         hr  50000.0
1    bob   NaN         IT  60000.0

In [442]:
df.tail(3)   #shows the last 3 raws

    name   age department   salary
3    eve  33.0         HR      NaN
4  david  40.0         IT  80000.0
5  alice  25.0         hr  50000.0

In [443]:
df.iloc[1:3, ]

      name   age department   salary
1      bob   NaN         IT  60000.0
2  charlie  35.0    finance  70000.0

In [444]:
#only  find department and  age in rows 1 to 3
df.loc[1:3,["department", "age"]]

  department   age
1         IT   NaN
2    finance  35.0
3         HR  33.0

In [445]:
# finding only some particular columns
df[["age", "salary"]]

    age   salary
0  25.0  50000.0
1   NaN  60000.0
2  35.0  70000.0
3  33.0      NaN
4  40.0  80000.0
5  25.0  50000.0

In [446]:
# To DROP a column .
df.drop("age", axis=1)

      name department   salary
0    alice         hr  50000.0
1      bob         IT  60000.0
2  charlie    finance  70000.0
3      eve         HR      NaN
4    david         IT  80000.0
5    alice         hr  50000.0

In [447]:
# The above function does not delete the column from the dataframe as when we print the dataframe it shows the original dataframe below.
df

      name   age department   salary
0    alice  25.0         hr  50000.0
1      bob   NaN         IT  60000.0
2  charlie  35.0    finance  70000.0
3      eve  33.0         HR      NaN
4    david  40.0         IT  80000.0
5    alice  25.0         hr  50000.0

In [448]:
# df.drop("age", axis=1, inplace=True) #the inplace remove the age column from the orginal dataframe.

In [449]:
df.shape

(6, 4)

In [450]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6 non-null      object
 1   age         5 non-null      float64
 2   department  6 non-null      object
 3   salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [451]:
df.describe()  #The percentages are outliers.

             age       salary
count   5.000000      5.00000
mean   31.600000  62000.00000
std     6.542171  13038.40481
min    25.000000  50000.00000
25%    25.000000  50000.00000
50%    33.000000  60000.00000
75%    35.000000  70000.00000
max    40.000000  80000.00000

In [452]:
# Broadcasting : exp, increase salary of all employees by 5000
df["salary"]= df["salary"]+5000
df

      name   age department   salary
0    alice  25.0         hr  55000.0
1      bob   NaN         IT  65000.0
2  charlie  35.0    finance  75000.0
3      eve  33.0         HR      NaN
4    david  40.0         IT  85000.0
5    alice  25.0         hr  55000.0

In [453]:
#Renaming collumns
df.rename(columns={"department":"dept"}, inplace=True) #inplace change the column name in the original dataframe
df

      name   age     dept   salary
0    alice  25.0       hr  55000.0
1      bob   NaN       IT  65000.0
2  charlie  35.0  finance  75000.0
3      eve  33.0       HR      NaN
4    david  40.0       IT  85000.0
5    alice  25.0       hr  55000.0

In [454]:
# print unique value data of a specific column
df['salary'].unique()

array([55000., 65000., 75000.,    nan, 85000.])

In [455]:
# number of employees in each department
df ["dept"].value_counts()

dept
hr         2
IT         2
finance    1
HR         1
Name: count, dtype: int64

In [456]:
# create a new column . Exp a column named promoted salary
df["promoted salary"]= df['salary']*5
df

      name   age     dept   salary  promoted salary
0    alice  25.0       hr  55000.0         275000.0
1      bob   NaN       IT  65000.0         325000.0
2  charlie  35.0  finance  75000.0         375000.0
3      eve  33.0       HR      NaN              NaN
4    david  40.0       IT  85000.0         425000.0
5    alice  25.0       hr  55000.0         275000.0

# **#Data cleaning**
two ways
1- drop the rows with null values
2- replace null values with some value (the most repeated values in the column)

In [457]:
# first we check null values
df.isnull().sum()

name               0
age                1
dept               0
salary             1
promoted salary    1
dtype: int64

In [458]:
# 1- first way : drop null values
df.dropna() #.This drops the null rows and the original dataframe is untouched.

      name   age     dept   salary  promoted salary
0    alice  25.0       hr  55000.0         275000.0
2  charlie  35.0  finance  75000.0         375000.0
4    david  40.0       IT  85000.0         425000.0
5    alice  25.0       hr  55000.0         275000.0

In [459]:
#2 -second way: replace null value
df['age'].fillna(df['age'].mean(), inplace=True)
df

/tmp/ipykernel_24189/4079823408.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace=True)

      name   age     dept   salary  promoted salary
0    alice  25.0       hr  55000.0         275000.0
1      bob  31.6       IT  65000.0         325000.0
2  charlie  35.0  finance  75000.0         375000.0
3      eve  33.0       HR      NaN              NaN
4    david  40.0       IT  85000.0         425000.0
5    alice  25.0       hr  55000.0         275000.0

In [460]:
df[['salary', 'promoted salary']] = df[['salary', 'promoted salary']].fillna(df[['salary', 'promoted salary']].median())
df

      name   age     dept   salary  promoted salary
0    alice  25.0       hr  55000.0         275000.0
1      bob  31.6       IT  65000.0         325000.0
2  charlie  35.0  finance  75000.0         375000.0
3      eve  33.0       HR  65000.0         325000.0
4    david  40.0       IT  85000.0         425000.0
5    alice  25.0       hr  55000.0         275000.0

In [461]:
# REPLACE a value
df["name"]=df["name"].replace("alice", "sharon")   #This will store the change in original dataframe
df

      name   age     dept   salary  promoted salary
0   sharon  25.0       hr  55000.0         275000.0
1      bob  31.6       IT  65000.0         325000.0
2  charlie  35.0  finance  75000.0         375000.0
3      eve  33.0       HR  65000.0         325000.0
4    david  40.0       IT  85000.0         425000.0
5   sharon  25.0       hr  55000.0         275000.0

In [462]:
#Duplicated values
df_dup=df[df.duplicated(keep="first")]  #keep=first is the parameter for the function duplicate and it keeps the first duplicated row
df_dup

     name   age dept   salary  promoted salary
5  sharon  25.0   hr  55000.0         275000.0

In [463]:
# invalie values:
#Lambda

df["promoted salary"]=df["promoted salary"].apply(lambda x: x/10 if x>30000 else x)   #x is input value and the out put valude is devided by 10.
df

      name   age     dept   salary  promoted salary
0   sharon  25.0       hr  55000.0          27500.0
1      bob  31.6       IT  65000.0          32500.0
2  charlie  35.0  finance  75000.0          37500.0
3      eve  33.0       HR  65000.0          32500.0
4    david  40.0       IT  85000.0          42500.0
5   sharon  25.0       hr  55000.0          27500.0

# Apply Method and lambda function
exp: multiply age by 2

In [464]:

#multiply age by 2
def multiply_age(x):
  return x*2

df["age"]= df['age'].apply(multiply_age)
df

      name   age     dept   salary  promoted salary
0   sharon  50.0       hr  55000.0          27500.0
1      bob  63.2       IT  65000.0          32500.0
2  charlie  70.0  finance  75000.0          37500.0
3      eve  66.0       HR  65000.0          32500.0
4    david  80.0       IT  85000.0          42500.0
5   sharon  50.0       hr  55000.0          27500.0