<a href="https://colab.research.google.com/github/fafa20252025/fariba/blob/main/pandasexercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
s= pd.Series([10,20,30,40,50])
s.name="calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [3]:
s.dtype

dtype('int64')

In [4]:
s.values

array([10, 20, 30, 40, 50])

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

**##indexing**

In [6]:
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [7]:
s[2:4]

2    30
3    40
Name: calories, dtype: int64

##ILOC find the location based on Numerical indexing

In [8]:
s.iloc[3]   #iloc function is only used for Numerical indices.

np.int64(40)

In [9]:
s.iloc[[1,2,3]]

1    20
2    30
3    40
Name: calories, dtype: int64

##To change the name of indecs

In [10]:
index=["apple","banana","grape","orange","strawberry"]
s.index=index   #s is an object and index is the attribute of object (s)
s

apple         10
banana        20
grape         30
orange        40
strawberry    50
Name: calories, dtype: int64

In [11]:
s["grape"]  # to find the calory of grapes

np.int64(30)

# LOC function is for finding label based indices.

In [12]:
s.loc["banana"]

np.int64(20)

in label base indexing, start and stop value are both included in output.

In [13]:
s["banana":"grapes"]

banana    20
grape     30
Name: calories, dtype: int64

# **##Creating series using a dictionary**

**1- create a dictionary**

In [14]:
fruit_protein = {
    "avodado" :2.3,
    "banana"  :1.2,
    "apple"   :1.3,
    "kiwi"    :2.1,
    "mango"   :2.4,
    "cherries":2.4
}

**2- create a series of the above dictionary**

In [15]:
s2=pd.Series(fruit_protein, name="protein")
s2

avodado     2.3
banana      1.2
apple       1.3
kiwi        2.1
mango       2.4
cherries    2.4
Name: protein, dtype: float64

# **Conditional selection**
exp: show all fruits that have protein over 2 grams
(Boolean indexing)

In [16]:
s2[s2>2]

avodado     2.3
kiwi        2.1
mango       2.4
cherries    2.4
Name: protein, dtype: float64

# **Logical operators**