<a href="https://colab.research.google.com/github/fafa20252025/fariba/blob/main/pandasexercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [550]:
import pandas as pd

In [551]:
s= pd.Series([10,20,30,40,50])
s.name="calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [552]:
s.dtype

dtype('int64')

In [553]:
s.values

array([10, 20, 30, 40, 50])

In [554]:
s.index

RangeIndex(start=0, stop=5, step=1)

**##indexing**

In [555]:
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [556]:
s[2:4]

2    30
3    40
Name: calories, dtype: int64

##ILOC find the location based on Numerical indexing

In [557]:
s.iloc[3]   #iloc function is only used for Numerical indices.

np.int64(40)

In [558]:
s.iloc[[1,2,3]]

1    20
2    30
3    40
Name: calories, dtype: int64

##To change the name of indecs

In [559]:
index=["apple","banana","grape","orange","strawberry"]
s.index=index   #s is an object and index is the attribute of object (s)
s

apple         10
banana        20
grape         30
orange        40
strawberry    50
Name: calories, dtype: int64

In [560]:
s["grape"]  # to find the calory of grapes

np.int64(30)

# LOC function is for finding label based indices.

In [561]:
s.loc["banana"]

np.int64(20)

in label base indexing, start and stop value are both included in output.

In [562]:
s["banana":"grapes"]

banana    20
grape     30
Name: calories, dtype: int64

# **##Creating series using a dictionary**

**1- create a dictionary**

In [563]:
fruit_protein = {
    "avodado" :2.3,
    "banana"  :1.2,
    "apple"   :1.3,
    "kiwi"    :2.1,
    "mango"   :2.4,
    "cherries":2.4
}

**2- create a series of the above dictionary**

In [564]:
s2=pd.Series(fruit_protein, name="protein")
s2  #print series

avodado     2.3
banana      1.2
apple       1.3
kiwi        2.1
mango       2.4
cherries    2.4
Name: protein, dtype: float64

# **Conditional selection**
exp: show all fruits that have protein over 2 grams
(Boolean indexing)

In [565]:
s2[s2>2]

avodado     2.3
kiwi        2.1
mango       2.4
cherries    2.4
Name: protein, dtype: float64

# **Logical operators**
True and True =True ,
True and False =False ,
False and False=False ,
True or True= True ,
True or False =True ,
False or Flase=Flse ,

In [566]:
# show fruits which have greater than 1 but have less than 2 gram protein.

s2[(s2>1)&(s2<2)]

banana    1.2
apple     1.3
Name: protein, dtype: float64

In [567]:
#not operation  not freater than 1.2
s2[~(s2>1.2)]

banana    1.2
Name: protein, dtype: float64

# **Modifying the series**

In [568]:
#modify the protein of a fruit
s2["banana"]=3
s2

avodado     2.3
banana      3.0
apple       1.3
kiwi        2.1
mango       2.4
cherries    2.4
Name: protein, dtype: float64

In [569]:
import numpy as np

In [570]:
ser= pd.Series(["a", np.nan, 1, np.nan, 2])
s.notnull().sum()

np.int64(5)

# **DataFrame**
 we only use LOC and ILOC functions in dataframe

In [571]:
# create dictionary
data={
    "name": ["alice", "bob", "charlie", "david","alice"],
    "age": [25, 30, 35, 40,25],
    "department": ["hr", "IT","finance","IT","hr"],
    "salary": [50000, 60000, 70000, 80000,50000]
}
data  #print data

{'name': ['alice', 'bob', 'charlie', 'david', 'alice'],
 'age': [25, 30, 35, 40, 25],
 'department': ['hr', 'IT', 'finance', 'IT', 'hr'],
 'salary': [50000, 60000, 70000, 80000, 50000]}

In [572]:
df=pd.DataFrame(data)  #convert the above dictionary to dataframe
df

      name  age department  salary
0    alice   25         hr   50000
1      bob   30         IT   60000
2  charlie   35    finance   70000
3    david   40         IT   80000
4    alice   25         hr   50000

In [573]:
df.head(2)  #print only first 2 rows

    name  age department  salary
0  alice   25         hr   50000
1    bob   30         IT   60000

In [574]:
df.tail(3)   #shows the last 3 raws

      name  age department  salary
2  charlie   35    finance   70000
3    david   40         IT   80000
4    alice   25         hr   50000

In [575]:
df.iloc[1:3, ]

      name  age department  salary
1      bob   30         IT   60000
2  charlie   35    finance   70000

In [576]:
#only  find department and  age in rows 1 to 3
df.loc[1:3,["department", "age"]]

  department  age
1         IT   30
2    finance   35
3         IT   40

In [577]:
# finding only some particular columns
df[["age", "salary"]]

   age  salary
0   25   50000
1   30   60000
2   35   70000
3   40   80000
4   25   50000

In [578]:
# To DROP a column .
df.drop("age", axis=1)

      name department  salary
0    alice         hr   50000
1      bob         IT   60000
2  charlie    finance   70000
3    david         IT   80000
4    alice         hr   50000

In [579]:
# The above function does not delete the column from the dataframe as when we print the dataframe it shows the original dataframe below.
df

      name  age department  salary
0    alice   25         hr   50000
1      bob   30         IT   60000
2  charlie   35    finance   70000
3    david   40         IT   80000
4    alice   25         hr   50000